CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_users_email_not_blank
        CHECK (BTRIM(email) <> ''),

    CONSTRAINT ck_users_email_normalized
        CHECK (email = LOWER(BTRIM(email))),

    CONSTRAINT ck_users_password_hash_not_blank
        CHECK (BTRIM(password_hash) <> '')
);

CREATE UNIQUE INDEX uq_users_email_ci
    ON users (LOWER(email));


CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_password_reset_tokens_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_password_reset_tokens_hash_not_blank
        CHECK (BTRIM(token_hash) <> ''),

    CONSTRAINT ck_password_reset_tokens_expiration
        CHECK (expires_at > created_at),

    CONSTRAINT ck_password_reset_tokens_used_at
        CHECK (used_at IS NULL OR used_at >= created_at)
);

CREATE UNIQUE INDEX uq_password_reset_tokens_token_hash
    ON password_reset_tokens (token_hash);

CREATE INDEX ix_password_reset_tokens_user_id
    ON password_reset_tokens (user_id);